name: flutter_raih_peduli
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.9
  rename: ^3.0.1
  intl: ^0.17.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash_screen.png"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: "assets/splash_screen.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf
        - asset: assets/fonts/Helvetica-BoldOblique.ttf
        - asset: assets/fonts/helvetica-light-587ebe5a59211.ttf
        - asset: assets/fonts/Helvetica-Oblique.ttf
        - asset: assets/fonts/Helvetica.ttf