name: flutter_raih_peduli
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  flutter_native_splash: ^2.3.5
  provider: ^6.0.5
  rename: ^3.0.1
  dio: ^5.3.3
  flutter_otp_text_field: ^1.1.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  quickalert: ^1.0.2
  email_validator: ^2.1.17

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash_screen.png"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: "assets/splash_screen.png"



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true

  
  assets:
    - assets/
    - assets/banner/
    - assets/icons/
    - assets/icons/home/
    - assets/icons/featuremenu/
  
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf
        - asset: assets/fonts/Helvetica-BoldOblique.ttf
        - asset: assets/fonts/helvetica-light-587ebe5a59211.ttf
        - asset: assets/fonts/Helvetica-Oblique.ttf
        - asset: assets/fonts/Helvetica.ttf
