name: flutter_raih_peduli
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.9
  rename: ^3.0.1
  intl: ^0.18.1
  dio: ^5.3.3
  flutter_otp_text_field: ^1.1.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  quickalert: ^1.0.2
  email_validator: ^2.1.17
  flutter_media_downloader: ^1.0.3
  url_launcher: ^6.2.2
  multi_select_flutter: ^4.1.3
  image_picker: ^1.0.4
  image_picker_platform_interface: ^2.9.1
  path: ^1.8.3
  permission_handler: ^11.1.0
  flutter_local_notifications: ^16.2.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  firebase_messaging: ^14.7.8
  palette_generator: ^0.3.3+3
  awesome_notifications: ^0.8.2
  image_gallery_saver: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.jpg"
  min_sdk_android: 21
  
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash_screen.png"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: "assets/splash_screen_12.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica-Bold.ttf
        - asset: fonts/Helvetica-BoldOblique.ttf
        - asset: fonts/helvetica-light-587ebe5a59211.ttf
        - asset: fonts/Helvetica-Oblique.ttf
        - asset: fonts/Helvetica.ttf
