name: flutter_raih_peduli
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  provider: ^6.0.5
  rename: ^3.0.1

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash_screen.png"
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    image: "assets/splash_screen.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
