// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7YQ6NB6a5Elbv3RH4k_aN7895SRX1K08',
    appId: '1:655476303847:web:3f7be9708fe35411dabf42',
    messagingSenderId: '655476303847',
    projectId: 'raihpeduli-92b4c',
    authDomain: 'raihpeduli-92b4c.firebaseapp.com',
    storageBucket: 'raihpeduli-92b4c.appspot.com',
    measurementId: 'G-BL7VBGQZCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyRDYGuZq7O8V4_ILxkw4kcIMDkTzMFXA',
    appId: '1:655476303847:android:1a1e0502f55fee60dabf42',
    messagingSenderId: '655476303847',
    projectId: 'raihpeduli-92b4c',
    storageBucket: 'raihpeduli-92b4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi52HSoyN37zdSq_CptZeqBXBepx74bDU',
    appId: '1:655476303847:ios:be52edd34114fe5bdabf42',
    messagingSenderId: '655476303847',
    projectId: 'raihpeduli-92b4c',
    storageBucket: 'raihpeduli-92b4c.appspot.com',
    iosBundleId: 'com.example.flutterRaihPeduli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi52HSoyN37zdSq_CptZeqBXBepx74bDU',
    appId: '1:655476303847:ios:2dd18a9c11ad2f80dabf42',
    messagingSenderId: '655476303847',
    projectId: 'raihpeduli-92b4c',
    storageBucket: 'raihpeduli-92b4c.appspot.com',
    iosBundleId: 'com.example.flutterRaihPeduli.RunnerTests',
  );
}
